config/routes.rb
MystroChef::Engine.routes.draw do
  resources :roles
  root to: "roles#index"
end

MystroServer::Application.routes.draw do
  mount MystroChef::Engine => "/plugins/chef"
end

app/models/compute.rb
class Compute
  has_and_belongs_to_many :roles, class_name: "MystroChef::Role"
end

app/models/jobs/chef/roles.rb
class Jobs::Chef::Roles < Job
  def work
    if Mystro.config.plugins.chef && defined?(Mystro::Plugin::Chef)
      list = Mystro::Plugin::Chef.role_list
      info "found #{list.count} roles"
      list.each do |name, url|
        info ".. #{name}"
        d = {
            description: url,
            internal: false
        }
        r = MystroChef::Role.where(name: name).first || MystroChef::Role.create(name: name)
        r.update_attributes(d)
      end
      info "complete"
    else
      warn "chef plugin disabled"
    end
  end
end

app/models/mystro_chef/role.rb
class MystroChef::Role
  include Mongoid::Document
  include Mongoid::Timestamps

  has_and_belongs_to_many :computes, class_name: "Compute"

  field :name, type: String
  field :description, type: String
  field :internal, type: Boolean, default: true
  field :deployable, type: Boolean, default: false

  index({ name: 1 }, { unique: true, background: true })

  scope :external, where(internal: false)
  scope :internal, where(internal: true)
  scope :deployable, where(deployable: true)

  class << self
    def create_from_fog(roles)
      out   = []
      return out unless roles
      rlist =
          case roles.class.name
            when "String"
              (roles || "").split(",")
            when "Array"
              roles
            else
              raise "role: create_from_fog: unknown type for roles [#{roles.class}]: #{roles.inspect}"
          end
      rlist.each do |r|
        out << Role.where(name: r).first || Role.create(name: r)
      end
      out
    end
  end
end

::Compute.has_and_belongs_to_many :roles, class_name: "MystroChef::Role"

app/controllers/mystro_chef/roles_controller.rb
class MystroChef::RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = MystroChef::Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = MystroChef::Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = MystroChef::Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = MystroChef::Role.find(params[:id])
  end

  # POST /roles                                                  ``
  # POST /roles.json
  def create
    @role = MystroChef::Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = MystroChef::Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = MystroChef::Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/views/mystro_chef/roles/_form.html.erb
<%= simple_form_for(@role, :html => {:class => "form-horizontal"}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :internal, :as => :boolean %>
      <%= f.input :deployable, :as => :boolean %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/mystro_chef/roles/edit.html.erb
<% content_for :subnav_buttons do %>
    <%= link_to 'Show', @role, :class => "btn" %>
    <%= link_to 'Back', roles_path, :class => "btn" %>
<% end %>
<%= render 'form' %>

app/views/mystro_chef/roles/index.html.erb
<table class="table table-condensed  table-striped table-hover  tablesorter {sortlist: [[0,0]]}">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Internal</th>
    <th>Deployable</th>
    <th class="links {sorter: false}"></th>
  </tr>
  </thead>
  <tbody>
<% @roles.each do |role| %>
  <tr>
    <td><%= link_to role.name, role_path(role) %></td>
    <td><%= role.description %></td>
    <td><%= role.internal %></td>
    <td><%= role.deployable %></td>
    <td class="links"><%= render "common/links", :obj => role, :edit => edit_role_path(role) %></td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/mystro_chef/roles/new.html.erb
<% content_for :subnav_buttons do %>
    <%= link_to 'Back', roles_path, :class => "btn" %>
<% end %>
<%= render 'form' %>

app/views/mystro_chef/roles/show.html.erb
<% content_for :subnav_buttons do %>
    <%= link_to edit_role_path(@role), :title => "Edit Role", :class => "btn btn-primary" do %><i class="icon-edit icon-white"></i> edit<% end %>
    <%= link_to @role, method: :delete, data: { confirm: 'Are you sure?' }, :title => "Destroy Role", :class => "btn btn-danger" do %><i class="icon-remove-sign icon-white"></i> destroy<% end %>
<% end %>

<table class="table table-condensed  table-striped table-hover fields-horizontal">
  <tr>
    <th>Name</th>
    <td><%= @role.name %></td>
  </tr>
  <tr>
    <th>Created</th>
    <td><%#= @role.created_at %></td>
  </tr>
</table>

<table class="table table-condensed  table-striped table-hover">
  <tr>
    <th>Computes</th>
  </tr>
  <% @role.computes.sort_by(&:short).each do |compute| %>
      <tr>
        <td><%= link_to compute.short, compute %></td>
      </tr>
  <% end %>
</table>